In [9]:
#importing all libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [10]:
#importing kaggle dataset
books=pd.read_csv("../data/raw/books.csv")
ratings=pd.read_csv("../data/raw/ratings.csv")
print(books.head())
print(ratings.head())

   id  book_id  best_book_id  work_id  books_count       isbn        isbn13  \
0   1  2767052       2767052  2792775          272  439023483  9.780439e+12
1   2        3             3  4640799          491  439554934  9.780440e+12
2   3    41865         41865  3212258          226  316015849  9.780316e+12
3   4     2657          2657  3275794          487   61120081  9.780061e+12
4   5     4671          4671   245494         1356  743273567  9.780743e+12

                       authors  original_publication_year  \
0              Suzanne Collins                     2008.0
1  J.K. Rowling, Mary GrandPr√©                     1997.0
2              Stephenie Meyer                     2005.0
3                   Harper Lee                     1960.0
4          F. Scott Fitzgerald                     1925.0

                             original_title  ... ratings_count  \
0                          The Hunger Games  ...       4780653
1  Harry Potter and the Philosopher's Stone  ...       4602479
2                                  Twilight  ...       3866839
3                     To Kill a Mockingbird  ...       3198671
4                          The Great Gatsby  ...       2683664

  work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
0            4942365                   155254      66715     127936
1            4800065                    75867      75504     101676
2            3916824                    95009     456191     436802
3            3340896                    72586      60427     117415
4            2773745                    51992      86236     197621

   ratings_3  ratings_4  ratings_5  \
0     560092    1481305    2706317
1     455024    1156318    3011543
2     793319     875073    1355439
3     446835    1001952    1714267
4     606158     936012     947718

                                           image_url  \
0  https://images.gr-assets.com/books/1447303603m...
1  https://images.gr-assets.com/books/1474154022m...
2  https://images.gr-assets.com/books/1361039443m...
3  https://images.gr-assets.com/books/1361975680m...
4  https://images.gr-assets.com/books/1490528560m...

                                     small_image_url
0  https://images.gr-assets.com/books/1447303603s...
1  https://images.gr-assets.com/books/1474154022s...
2  https://images.gr-assets.com/books/1361039443s...
3  https://images.gr-assets.com/books/1361975680s...
4  https://images.gr-assets.com/books/1490528560s...

[5 rows x 23 columns]
   book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [19]:
books.shape,ratings.shape

((10000, 23), (981756, 3))

In [11]:
books.isnull().sum()

id                              0
book_id                         0
best_book_id                    0
work_id                         0
books_count                     0
isbn                          700
isbn13                        585
authors                         0
original_publication_year      21
original_title                585
title                           0
language_code                1084
average_rating                  0
ratings_count                   0
work_ratings_count              0
work_text_reviews_count         0
ratings_1                       0
ratings_2                       0
ratings_3                       0
ratings_4                       0
ratings_5                       0
image_url                       0
small_image_url                 0
dtype: int64

In [12]:
ratings["rating"].describe()

count    981756.000000
mean          3.856534
std           0.983941
min           1.000000
25%           3.000000
50%           4.000000
75%           5.000000
max           5.000000
Name: rating, dtype: float64

In [16]:
book_ratings=ratings.groupby('book_id').agg(
    avg_rating=('rating','mean'),
    num_of_ratings=('rating','count')).reset_index()
book_ratings.head()

   book_id  avg_rating  num_of_ratings
0        1        4.24             100
1        2        4.21             100
2        3        3.09             100
3        4        4.46             100
4        5        3.89             100

In [20]:
#merging both datasets
book_ratings=book_ratings.merge(books,on="book_id")
book_ratings.head()

,book_id,avg_rating,num_of_ratings,id_x,best_book_id_x,work_id_x,books_count_x,isbn_x,isbn13_x,authors_x,...,ratings_count_y,work_ratings_count_y,work_text_reviews_count_y,ratings_1_y,ratings_2_y,ratings_3_y,ratings_4_y,ratings_5_y,image_url_y,small_image_url_y
0,1,4.24,100,27,1,41335427,275,439785960,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",...,1678823,1785676,27520,7308,21516,136333,459028,1161491,https://images.gr-assets.com/books/1361039191m...,https://images.gr-assets.com/books/1361039191s...
1,2,4.21,100,21,2,2809203,307,439358078,9.780439e+12,"J.K. Rowling, Mary GrandPr√©",...,1735368,1840548,28685,9528,31577,180210,494427,1124806,https://images.gr-assets.com/books/1387141547m...,https://images.gr-assets.com/books/1387141547s...
2,3,3.09,100,2,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
3,5,3.89,100,18,5,2402163,376,043965548X,9.780440e+12,"J.K. Rowling, Mary GrandPr√©, Rufus Beck",...,1832823,1969375,36099,6716,20413,166129,509447,1266670,https://images.gr-assets.com/books/1499277281m...,https://images.gr-assets.com/books/1499277281s...
4,6,4.09,100,24,6,3046572,332,439139600,9.780439e+12,"J.K. Rowling, Mary GrandPr√©",...,1753043,1868642,31084,6676,20210,151785,494926,1195045,https://images.gr-assets.com/books/1361482611m...,https://images.gr-assets.com/books/1361482611s...

In [24]:
#rarely rated books
rarely_rated_books=book_ratings[book_ratings['num_of_ratings']>=50]
rarely_rated_books.tail()

,book_id,avg_rating,num_of_ratings,id_x,best_book_id_x,work_id_x,books_count_x,isbn_x,isbn13_x,authors_x,...,ratings_count_y,work_ratings_count_y,work_text_reviews_count_y,ratings_1_y,ratings_2_y,ratings_3_y,ratings_4_y,ratings_5_y,image_url_y,small_image_url_y
807,9914,3.936170,94,5973,9914,1308950,21,330339184,9.780330e+12,Bret Easton Ellis,...,12898,14674,477,596,2100,5342,4324,2312,https://images.gr-assets.com/books/1374684746m...,https://images.gr-assets.com/books/1374684746s...
808,9915,3.677778,90,1908,9915,1146200,96,679781498,9.780680e+12,Bret Easton Ellis,...,45978,51208,2684,1820,5379,15400,18292,10317,https://images.gr-assets.com/books/1443060100m...,https://images.gr-assets.com/books/1443060100s...
809,9943,4.460674,89,3140,9943,3014463,30,084230052X,9.780842e+12,Francine Rivers,...,29250,30412,1083,321,949,4364,9593,15185,https://images.gr-assets.com/books/1406513472m...,https://images.gr-assets.com/books/1406513472s...
810,9957,3.336957,92,6283,9957,1189398,43,99468387,9.780099e+12,Ian McEwan,...,14418,18301,1343,629,1845,5691,6733,3403,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...
811,9998,4.326316,95,8114,9998,58336,90,679733787,9.780680e+12,"K≈çb≈ç Abe, E. Dale Saunders",...,11467,13886,1026,264,838,3046,5523,4215,https://images.gr-assets.com/books/1361254930m...,https://images.gr-assets.com/books/1361254930s...

In [31]:
#Sorting the books on the basis of average ratings
Top_rated_books=rarely_rated_books.sort_values(by="avg_rating",ascending=False).head(20)
Top_rated_books.head()

,book_id,avg_rating,num_of_ratings,id_x,best_book_id_x,work_id_x,books_count_x,isbn_x,isbn13_x,authors_x,...,ratings_count_y,work_ratings_count_y,work_text_reviews_count_y,ratings_1_y,ratings_2_y,ratings_3_y,ratings_4_y,ratings_5_y,image_url_y,small_image_url_y
769,9566,4.777778,99,1299,9566,1105809,40,184243022X,9.781842e+12,Tom Robbins,...,56802,61511,2462,960,2789,11834,23239,22689,https://images.gr-assets.com/books/1308749778m...,https://images.gr-assets.com/books/1308749778s...
354,4708,4.660000,100,3255,4708,2432116,522,743451503,9.780743e+12,F. Scott Fitzgerald,...,26597,33692,2050,632,2522,9543,12851,8144,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...
771,9569,4.618557,97,4872,9569,2124286,40,1842431021,9.781842e+12,Tom Robbins,...,14206,15763,642,306,1431,5022,5721,3283,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...
762,9531,4.557143,70,3910,9531,3204657,42,078683787X,9.780787e+12,"Dave Barry, Ridley Pearson, Greg Call",...,29555,30821,1289,310,951,5480,11230,12850,https://s.gr-assets.com/assets/nophoto/book/11...,https://s.gr-assets.com/assets/nophoto/book/50...
291,3885,4.550000,100,6663,3885,7609,7,898214971,9.780898e+12,"Janet Briggs, Beth Wittlinger",...,14469,14543,38,185,493,2219,4215,7431,https://images.gr-assets.com/books/1309198140m...,https://images.gr-assets.com/books/1309198140s...

In [44]:
Top_rated_books=rarely_rated_books.assign(
    score=rarely_rated_books["avg_rating"]*(rarely_rated_books["num_of_ratings"]/
    (rarely_rated_books["num_of_ratings"]).max())
).sort_values(by="score",ascending=False).head(20)  
Top_rated_books.head()
columns=Top_rated_books.columns
print(columns)

Index(['book_id', 'avg_rating', 'num_of_ratings', 'id_x', 'best_book_id_x',
       'work_id_x', 'books_count_x', 'isbn_x', 'isbn13_x', 'authors_x',
       'original_publication_year_x', 'original_title_x', 'title_x',
       'language_code_x', 'average_rating_x', 'ratings_count_x',
       'work_ratings_count_x', 'work_text_reviews_count_x', 'ratings_1_x',
       'ratings_2_x', 'ratings_3_x', 'ratings_4_x', 'ratings_5_x',
       'image_url_x', 'small_image_url_x', 'id_y', 'best_book_id_y',
       'work_id_y', 'books_count_y', 'isbn_y', 'isbn13_y', 'authors_y',
       'original_publication_year_y', 'original_title_y', 'title_y',
       'language_code_y', 'average_rating_y', 'ratings_count_y',
       'work_ratings_count_y', 'work_text_reviews_count_y', 'ratings_1_y',
       'ratings_2_y', 'ratings_3_y', 'ratings_4_y', 'ratings_5_y',
       'image_url_y', 'small_image_url_y', 'score'],
      dtype='object')

In [47]:
print(Top_rated_books[["original_title_y","title_y","authors_x","avg_rating","num_of_ratings"]])

                                      original_title_y  \
769                         Still Life with Woodpecker
354                           The Beautiful and Damned
291                         The Taste of Home Cookbook
206  A People's History of the United States: 1492 ...
210                          Girl with a Pearl Earring
95                                     Deception Point
448                        Hard Times: For These Times
134  The Curious Incident of the Dog in the Night-Time
771                                    Villa Incognito
450                                     The Last Juror
324  First They Killed My Father: A Daughter of Cam...
96   The Millionaire Next Door: The Surprising Secr...
217                 The Adventures of Huckleberry Finn
269                                 The Quiet American
602                                The Android's Dream
203                                                NaN
370    Three Men in a Boat (To Say Nothing of the Dog)
719                              The War of the Worlds
406                                   Franny and Zooey
540                  His Excellency: George Washington

                                               title_y  \
769                         Still Life with Woodpecker
354                           The Beautiful and Damned
291                         The Taste of Home Cookbook
206            A People's History of the United States
210                          Girl with a Pearl Earring
95                                     Deception Point
448                                         Hard Times
134  The Curious Incident of the Dog in the Night-Time
771                                    Villa Incognito
450                                     The Last Juror
324  First They Killed My Father: A Daughter of Cam...
96   The Millionaire Next Door: The Surprising Secr...
217                 The Adventures of Huckleberry Finn
269                                 The Quiet American
602                                The Android's Dream
203                      The Lost Boy (Dave Pelzer #2)
370                Three Men in a Boat (Three Men, #1)
719                              The War of the Worlds
406                                   Franny and Zooey
540                  His Excellency: George Washington

                                 authors_x  avg_rating  num_of_ratings
769                            Tom Robbins    4.777778              99
354                    F. Scott Fitzgerald    4.660000             100
291          Janet Briggs, Beth Wittlinger    4.550000             100
206                            Howard Zinn    4.540000             100
210                        Tracy Chevalier    4.530000             100
95                               Dan Brown    4.500000             100
448                        Charles Dickens    4.535354              99
134                            Mark Haddon    4.480000             100
771                            Tom Robbins    4.618557              97
450                           John Grisham    4.470000             100
324                              Loung Ung    4.450000             100
96     Thomas J. Stanley, William D. Danko    4.440000             100
217  Mark Twain, John Seelye, Guy Cardwell    4.440000             100
269           Graham Greene, Robert  Stone    4.430000             100
602                            John Scalzi    4.410000             100
203                            Dave Pelzer    4.400000             100
370                       Jerome K. Jerome    4.400000             100
719           H.G. Wells, Arthur C. Clarke    4.390000             100
406                          J.D. Salinger    4.390000             100
540                        Joseph J. Ellis    4.390000             100